/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calcul.h"

void *
calcul_null_1_svc(void *argp, struct svc_req *rqstp)
{
	static char * result;

	/*
	 * insert server code here
	 */

	return (void *) &result;
}

reponse *
calcul_my_strcat_1_svc(data *argp, struct svc_req *rqstp)
{
	static reponse  result;
	int size = strlen(argp->arg1) + strlen(argp->arg2);
	char *rep = malloc((size+1)*sizeof(char));
	strcat(rep,argp->arg1);
	strcat(rep, argp->arg2);
	result.concat = strcat(argp->arg1,argp->arg2);
	return &result;
}
