/*
 * This is sample code generated by rpcgen.
 * hese are only templates and you can use them
 * as a guideline for developing your own functions.
 */
#include "string.h"
#include "calcul.h"
CLIENT *clnt;

char * concatenate (char* a, char* b) {
	reponse *resultat;
	data parametre;
	parametre.arg1 = a;
	parametre.arg2 = b;
	resultat = calcul_my_strcat_1 (&parametre, clnt); 
	return resultat->concat;
}//concatenate


void
calcul_1(char *host)
{
	CLIENT *clnt;
	void  *result_1;
	char *calcul_null_1_arg;
	reponse  *result_2;
	data  calcul_my_strcat_1_arg;
#ifndef	DEBUG
	clnt = clnt_create (host, CALCUL, VERSION_UN, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = calcul_null_1((void*)&calcul_null_1_arg, clnt);
	if (result_1 == (void *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_2 = calcul_my_strcat_1(&calcul_my_strcat_1_arg, clnt);
	if (result_2 == (reponse *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;
	char a[30];
	char b[30];
	char *pos;
	char *pos2;
	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	clnt = clnt_create (host, CALCUL, VERSION_UN, "tcp"); 
	printf("String 1 : ");
	fgets(a,30,stdin);
	printf("String 2 : ");
	fgets(b,30,stdin);
	if ((pos=strchr(a, '\n')) != NULL) *pos = '\0';
	if ((pos2=strchr(b, '\n')) != NULL) *pos2 = '\0';
	printf("String concat = %s\n", concatenate(a, b));
	exit (0);
}
