/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "http.h"
#include <sys/types.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <arpa/inet.h>
#include <unistd.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <netdb.h>


int checkQuery(char *query){
	reponse *resultat;
	data1 http_request1_1_arg;
  	 /* Demande de rentrer un message */
  	memcpy(&http_request1_1_arg.request, &query, sizeof(query));
  	resultat = http_request1_1(&http_request1_1_arg, clnt);
  	return resultat->fd;
}

int read_file(int fd){
	reponse *resultat;
	data2 http_request2_1_arg;
	http_request2_1_arg.fd = fd;
	resultat = http_request2_1(&http_request2_1_arg, clnt);
	return resultat;
}


void
http_1(char *host)
{
	CLIENT *clnt;
	void  *result_1;
	char *http_null_1_arg;
	response  *result_2;
	data1  http_request1_1_arg;
	response  *result_3;
	data2  http_request2_1_arg;
	

#ifndef	DEBUG
	clnt = clnt_create (host, HTTP, VERSION_UN, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = http_null_1((void*)&http_null_1_arg, clnt);
	if (result_1 == (void *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_2 = http_request1_1(&http_request1_1_arg, clnt);
	if (result_2 == (response *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	
	result_3 = http_request2_1(&http_request2_1_arg, clnt);
	if (result_3 == (response *) NULL) {
		clnt_perror (clnt, "call failed");
	}

#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	http_1 (host);

exit (0);
}
