/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */


#include "http.h"

void *
http_null_1_svc(void *argp, struct svc_req *rqstp)
{
  static char * result;

  /*
   * insert server code here
   */

  return (void *) &result;
}

response *
http_request1_1_svc(data1 *argp, struct svc_req *rqstp)
{
	static response  result;
	char *pos;
	char buffer[256];
	char root[256] = "public_html";
	FILE* fichier;

  /* Verification de la demande*/
  char *tok = strtok(argp->request, " ");
  if(strcmp(tok, "GET") == 0){
      printf("Requete acceptée\n");
  		//On récupère la page demandée dans tok
      tok = strtok(NULL, " ");
      if(strcmp(tok, "/") == 0){
          strcat(tok, "index.html");
      }
      strcat(root, tok);
      printf("Tentative d'ouverture de -%s-\n",root);
			fichier = fopen(root, "r");
			if(fichier == NULL){//Le fichier demandé n'existe pas
				result.fd=-1;
			}
	}else{
      printf("Requete rejetée\n");
			result.fd=-1;
  }
 	return &result;
}

response *
http_request2_1_svc(data2 *argp, struct svc_req *rqstp)
{
  char *buffer;
	static response  result;
	if (argp->fd != -1){
      result.fd = argp->fd;
  		printf("Envoi des données...\n");
      fgets(buffer,BUFFER_SIZE,(FILE *)argp->fd);
      strcpy(result.char_read,buffer);
			// fclose(fichier) close après que tout a était lu
	}
	return &result;
}
