/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */


#include "http.h"
#include <unistd.h>
#include <fcntl.h>

void *
http_null_1_svc(void *argp, struct svc_req *rqstp)
{
  static char * result;

  /*
   * insert server code here
   */

  return (void *) &result;
}

response *
http_request1_1_svc(data1 *argp, struct svc_req *rqstp)
{
	static response  result;
	char *pos;
	char buffer[256];
	char root[256] = "public_html";
	int fichier;

  /* Verification de la demande*/
  char *tok = strtok(argp->request, " ");
  if(strcmp(tok, "GET") == 0){
      printf("Requete acceptée\n");
  		//On récupère la page demandée dans tok
      tok = strtok(NULL, " ");
      if(strcmp(tok, "/") == 0){
          strcat(tok, "index.html");
      }
      strcat(root, tok);
      printf("Tentative d'ouverture de -%s-\n",root);
			fichier = open(root, O_RDONLY);
      result.fd = fichier;
			if(fichier == -1){//Le fichier demandé n'existe pas
				result.fd=-1;
			}
	}else{
      printf("Requete rejetée\n");
			result.fd=-1;
  }
 	return &result;
}

response *
http_request2_1_svc(data2 *argp, struct svc_req *rqstp)
{
  char *buffer;
	static response  result;
  int byteRead=-1;
	if (argp->fd != -1){
      result.fd = argp->fd;
      byteRead=read(argp->fd,buffer,BUFFER_SIZE);
      result.byte_read_nbr = byteRead;
      strcpy(result.char_read,buffer);
      if(byteRead == 0){ // Si on arrive au bout du fichier on le ferme
        close(argp->fd);
      }
	}
	return &result;
}
