/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "http.h"
#include <unistd.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
CLIENT *clnt;

void read_file(char *host){
	response *resultat;
	data2 http_request2_1_arg;
	data1 request1;
	char ressource [256]="";
	printf("%s\n", "Entrer la ressource désirée (par default : index.html):");
	fgets(ressource,sizeof(ressource),stdin);
	if(strlen(ressource) == 1){
		strcpy(ressource,"index.html");
	}
	//supprimer les retours à la ligne
	strtok(ressource, "\n");

	char *header;
	header = malloc(sizeof(ressource));
	strcpy(header,"GET /");
	strcat(header,ressource);
	strcat(header," HTTP/1.1\r\nHost: ");
	strcat(header,host);
	strcat(header,"\r\n\r\n");

	strcpy(request1.request,header);
	http_request2_1_arg.fd = http_request1_1(&request1, clnt)->fd;
	if(http_request2_1_arg.fd == -1){
		printf("%s\n", "Le fichier n'existe pas");
	}else{
			do {
				resultat = http_request2_1(&http_request2_1_arg,clnt);
				printf("%s\n",resultat->char_read);
			} while(resultat->byte_read_nbr<20);
	}
}


void
http_1(char *host)
{
	CLIENT *clnt;
	void  *result_1;
	char *http_null_1_arg;
	response  *result_2;
	data1  http_request1_1_arg;
	response  *result_3;
	data2  http_request2_1_arg;


#ifndef	DEBUG
	clnt = clnt_create (host, HTTP, VERSION_UN, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = http_null_1((void*)&http_null_1_arg, clnt);
	if (result_1 == (void *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_2 = http_request1_1(&http_request1_1_arg, clnt);
	if (result_2 == (response *) NULL) {
		clnt_perror (clnt, "call failed");
	}

	result_3 = http_request2_1(&http_request2_1_arg, clnt);
	if (result_3 == (response *) NULL) {
		clnt_perror (clnt, "call failed");
	}

#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	clnt = clnt_create (host, HTTP, VERSION_UN, "udp");
	read_file(host);

exit (0);
}
